import fs from "node:fs/promises";

import openapiTS, { astToString } from "openapi-typescript";

const GENERATED_HEADER = `// Generated by @bff/api-contract. DO NOT EDIT.\n`;

function validateSchema(schema) {
  if (schema === null || typeof schema !== "object" || Array.isArray(schema)) {
    throw new TypeError("OpenAPI schema must be a JSON object");
  }

  if (typeof schema.openapi !== "string" || !schema.openapi.startsWith("3.")) {
    throw new Error("OpenAPI schema must declare an OpenAPI 3.x version");
  }

  if (schema.paths === null || typeof schema.paths !== "object" || Array.isArray(schema.paths)) {
    throw new Error("OpenAPI schema must contain a paths object");
  }
}

export async function generateContractFromSchema(schema) {
  validateSchema(schema);

  const ast = await openapiTS(schema);
  const generated = astToString(ast).replaceAll("\r\n", "\n").trimEnd();

  return `${GENERATED_HEADER}${generated}\n`;
}

export async function generateContractFromFile(schemaPath) {
  const raw = await fs.readFile(schemaPath, "utf8");

  let schema;
  try {
    schema = JSON.parse(raw);
  } catch (error) {
    throw new Error(`OpenAPI schema is not valid JSON: ${schemaPath}`, { cause: error });
  }

  return generateContractFromSchema(schema);
}

export { GENERATED_HEADER, validateSchema };
